apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-production

resources:
- ../../base
- hpa.yaml

patches:
- path: patch-deployment.yaml
- path: hpa.yaml

labels:
- pairs:
    environment: production

images:
- name: api-service
  newName: salilkayastha/api-service
  newTag: main-7cbe81e
- name: frontend-service
  newName: salilkayastha/frontend-service
  newTag: main-7cbe81e
- name: worker-service
  newName: salilkayastha/worker-service
  newTag: main-7cbe81e

configMapGenerator:
- behavior: merge
  literals:
  - NODE_ENV=production
  - LOG_LEVEL=info
  name: app-config
