apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-app-production

resources:
  - ../../base
  - hpa.yaml

patches:
  - path: patch-deployment.yaml
  - path: hpa.yaml

labels:
  - pairs:
      environment: production

images:
  - name: api-service
    newTag: production
  - name: worker-service
    newTag: production
  - name: frontend-service
    newTag: production

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
