apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "db-service"
  DB_NAME: "appdb"
  DB_PORT: "5432"
  API_PORT: "3000"
  REACT_APP_API_URL: "http://api-service:3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # postgres (base64)
  DB_PASSWORD: cGFzc3dvcmQ=  # password (base64)
  POSTGRES_USER: cG9zdGdyZXM=  # postgres (base64)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password (base64)