apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-app

resources:
  - configmap.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: microservices-app
      environment: base

images:
  - name: api-service
    newName: api-service
    newTag: latest
  - name: worker-service
    newName: worker-service
    newTag: latest
  - name: frontend-service
    newName: frontend-service
    newTag: latest